### ISSUE TITLE
Missing Dependencies

### ISSUE THREAD

**Issue by craigastewart** [ghpaetzold/questplusplus#40]
Hi all,

I'm attempting to add a new feature and have followed the example in the manual; I've created a Processor class, updated the SentenceLevelProcessorFactory and created the new Feature class.

Unfortunately I'm getting the following error:
********** Producing output **********
Feature 7001 cannot run because some of its dependencies are missing.

Any ideas what I might be missing?

Thanks!

**Comment by ghpaetzold** [comment]
Hi Craig,


So I suspect you added some resources to your feature through the function "this.addResource(resource_name)", right?

The first thing to check would be that all "resource_name" resources are included in  your configuration file. Could that be the problem maybe?


_______________________________

Gustavo Henrique Paetzold
Research Associate in Text Adaptation
University of Sheffield
________________________________
De: craigastewart <notifications@github.com>
Enviado: segunda-feira, 22 de janeiro de 2018 19:01:38
Para: ghpaetzold/questplusplus
Cc: Subscribed
Assunto: [ghpaetzold/questplusplus] Missing Dependencies (#40)


Hi all,

I'm attempting to add a new feature and have followed the example in the manual; I've created a Processor class, updated the SentenceLevelProcessorFactory and created the new Feature class.

Unfortunately I'm getting the following error:
********** Producing output **********
Feature 7001 cannot run because some of its dependencies are missing.

Any ideas what I might be missing?

Thanks!

**Comment by craigastewart** [comment]
Hi Gustavo,

I'd not updated the config file correctly - seems to be working now thanks for your help.

Craig
