### ISSUE TITLE
lm and giza features showing dependencies missing

### ISSUE THREAD

**Issue by kashifshah** [ghpaetzold/questplusplus#7]

**Comment by kashifshah** [comment]
10 out of 17 baseline features are working now (including LM and Giza based features) .. other 7 features are most probably  not either registered or incorrectly named,

**Comment by carolscarton** [comment]
What was the problem, @kashifshah?

On 25 August 2015 at 22:49, kashifshah notifications@github.com wrote:

> 10 out of 17 baseline features are working now (including LM and Giza
> based features) .. other 7 features are most probably not either registered
> or incorrectly named,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghpaetzold/questplusplus/issues/7#issuecomment-134751613
> .

## 

_Carolina Scarton_
PhD Candidate and Research Assistant
Department of Computer Science
University of Sheffield
http://www.dcs.shef.ac.uk/~carolina

**Comment by kashifshah** [comment]
Apparently, the LM resources were not registered in SentenceLevelProcessorFactory. I added following in  getLMProcessors() and it seems to work now.
ResourceManager.registerResource("source.lm");
ResourceManager.registerResource("target.lm");

**Comment by carolscarton** [comment]
Thanks Kashif!

I took a look on the features that are still with some problems. I believe
the reason is the same. These features are related to ngramcounts and the
registered resource is wrong ("ngramcount", it should be "source.ngram")

On 25 August 2015 at 23:33, kashifshah notifications@github.com wrote:

> Apparently, the LM resources were not registered in
> SentenceLevelProcessorFactory. I added following in getLMProcessors() and
> it seems to work now.
> ResourceManager.registerResource("source.lm");
> ResourceManager.registerResource("target.lm");
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/ghpaetzold/questplusplus/issues/7#issuecomment-134761009
> .

## 

_Carolina Scarton_
PhD Candidate and Research Assistant
Department of Computer Science
University of Sheffield
http://www.dcs.shef.ac.uk/~carolina
